[workspace]
resolver = "2"
members = [
    "fontique",
    "parley",
    "examples/tiny_skia_render",
    "examples/swash_render",
]

[workspace.package]
edition = "2021"
# Keep in sync with RUST_MIN_VER in .github/workflows/ci.yml and with the relevant README.md files.
rust-version = "1.70"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/linebender/parley"

[workspace.lints]
clippy.doc_markdown = "warn"
clippy.semicolon_if_nothing_returned = "warn"
clippy.trivially_copy_pass_by_ref = "warn"
rust.unused_qualifications = "warn"

[workspace.dependencies]
fontique = { version = "0.1.0", default-features = false, path = "fontique" }
parley = { version = "0.1.0", default-features = false, path = "parley" }
skrifa = { version = "0.19.1", default-features = false }
peniko = { version = "0.1.0", default-features = false }
